### ISSUE TITLE
Error running example locally using Ollama

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/serverless-chat-langchainjs#50]
**Describe the issue:**
Using Ollama to run the example locally, opening the web http://localhost:8000 chat fails with the following error:
![image](https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/138103031/31feabba-9739-4331-a1d0-8768c49eea3b)
![image](https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/138103031/0aa7ec86-03d3-423b-b5af-67299e4f7d7a)

**Repro Steps:**

1. Run command `git clone https://github.com/Azure-Samples/serverless-chat-langchainjs.git`
2. Install and run [Ollama](https://ollama.com/)
3. Run command `ollama pull mistral` and `ollama pull all-minilm:l6-v2`
4. Run command `npm install`
5. Run command `npm start`
6. Run command `npm run upload:docs`
7. Open the URL http://localhost:8000

**Environments:**

- azd version: azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)
- os: windows

**Expected behavior:**
Open the URL http://localhost:8000 in the browser and successfully start chatting with the bot

@sinedied for notification.

**Comment by sinedied** [comment]
@NanaXiong00 Thanks for the report! could you check that Ollama is working correctly? I frequently have to restart it manually because of updates. You can check if it works by running the command:

```
ollama run mistral
```
If the model starts and you can chat with it, it should be good. If not, try restarting Ollama.

From the logs, it also seems that you tried testing the chat before the document where ingested (running `npm run upload:docs`). Seems like the ingestion worked, did you try again the chat after that?

**Comment by NanaXiong00** [comment]
Follow the above reply and test again. The problem cannot be reproduced, so I closed it.
