### ISSUE TITLE
[docs] Translate tutorial file to other languages

### ISSUE THREAD

**Issue by tanersekmen** [Azure-Samples/serverless-chat-langchainjs#51]
> ## Please provide us with the following information:
Your tutorial looks promising, but have you considered translating it into different languages? If so, do you have a timeframe for that? I'd be willing to help with translating it into Turkish.

### This issue is for a: (mark with an `x`)

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### OS and Version?

> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions

>

### Mention any other details that might be useful

> ---
>
> Thanks! We'll be in touch soon.

**Comment by glaucia86** [comment]
Hi @tanersekmen, what's up?

Yes, we intend to turn this tutorial into official documentation. As soon as it's ready (we believe that before Microsoft Build this content will be ready), we'll be making it available to the entire community as soon as possible.

And @tanersekmen, I'd like to hear your feedback, does the content written so far sound understandable? Anything we need to improve? Any topics related to the project that we haven't written about in the theoretical part that need further clarification?

Why these questions? Because AI is a new topic for all of us (whether we're beginners or Advanced Developers) and it's constantly changing. And we want everyone to be able to benefit from this material

**Comment by tanersekmen** [comment]
Hi @glaucia86, I am good, you?

I believe that the current explanation and expression in both the 'setting-up' extension tutorial file and the general documentation are sufficient and well-articulated. I haven't encountered any uncertainties in my understanding. My only consideration was regarding translations into different languages, which is why I wanted to raise this issue in this manner.


I completely agree with you, but if you were to ask me, the tutorial and documentation seem quite satisfactory.

**Comment by glaucia86** [comment]
Awesome, @tanersekmen !
Thank you for your feedback. I always try to ask for improvements, because the material is just right for the audience.
Let me just see internally how these documents will proceed, whether they will be translated automatically or will need people to translate them. As soon as I have the answer, I'll ask for your help to translate it, yes! :)

**Comment by tanersekmen** [comment]
Thank you for your message @glaucia86 . I would be glad to assist with translation if human preference is desired. Take care 👍
