### ISSUE TITLE
[docs]: Add Documentation Step - Execute `npm run upload:docs` before deployment to azure

### ISSUE THREAD

**Issue by glaucia86** [Azure-Samples/serverless-chat-langchainjs#74]
> ## Please provide us with the following information:

### This issue is for a: (mark with an `x`)

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### OS and Version?

> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions

>

### Mention any other details that might be useful

Include in the documentation that before deploying the application, the user must execute the command: npm run upload:docs. Why? So that the pdf files can be sent to Azure Blob Storage and thus be able to generate the answers coming from the chat.

After executing this command, the user will be able to get the responses back once the application has been deployed to Azure.

Today the README.md says that: (the actual instruction is under the local section). So in this case we can move it to the deployed application or copy it.

```bash
azd auth login
azd up
```

**note**: remember that in order for you to be able to read these pdf files after the application has been deployed, you need to provision the Azure services first. Otherwise, you won't be able to upload these files to Blob Storage 

> Thanks! We'll be in touch soon.

**Comment by sinedied** [comment]
The script `npm run upload:docs` is only needed when running locally, not on Azure.

Uploading the documents occurs in the postup hook, as the application needs to be deployed first otherwise the uploading won't work. See https://github.com/Azure-Samples/serverless-chat-langchainjs/blob/main/azure.yaml#L35-L41

If the document upload does not work when `azd up` runs, then it's a different issue. I've noticed this might occur on Windows when using an old (< v7) Powershell version

**Comment by sinedied** [comment]
Changed this issue to bug, as document uploading should happen automatically

**Comment by glaucia86** [comment]
> Changed this issue to bug, as document uploading should happen automatically

Thanks for the reply, @sinedied
